Resources:  
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: random-string-cluster
  DemoECSTask:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      Family: random-string-task
      NetworkMode: awsvpc
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: arn:aws:iam::623127157773:role/ecsTaskExecutionRole
      ContainerDefinitions: 
        - Name: random-string-container
          Image: 623127157773.dkr.ecr.ap-southeast-1.amazonaws.com/random-string-image:latest
          PortMappings: 
            - ContainerPort: 8000
              HostPort: 8000
            - ContainerPort: 80
              HostPort: 80
          Memory: 512
          Essential: true
          Privileged: false
      RequiresCompatibilities:
        - FARGATE